version = 4.2.0
archive_dir = /etc/letsencrypt/archive/regen.gaiaai.xyz
cert = /etc/letsencrypt/live/regen.gaiaai.xyz/cert.pem
privkey = /etc/letsencrypt/live/regen.gaiaai.xyz/privkey.pem
chain = /etc/letsencrypt/live/regen.gaiaai.xyz/chain.pem
fullchain = /etc/letsencrypt/live/regen.gaiaai.xyz/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = b7c690ef058ad2de576c613311d79d82
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
