# Generated by Django 5.2.4 on 2025-07-16 19:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.UUIDField(unique=True)),
                ("agent_name", models.CharField(max_length=255)),
                (
                    "deployment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_interactions", models.IntegerField(default=0)),
                ("total_documents_processed", models.IntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "agent_metrics",
                "ordering": ["-deployment_date"],
            },
        ),
        migrations.CreateModel(
            name="DocumentMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.UUIDField(blank=True, null=True)),
                ("document_id", models.CharField(max_length=255)),
                ("document_path", models.TextField()),
                ("document_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=500)),
                ("confidence_level", models.CharField(blank=True, max_length=50)),
                (
                    "processed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "document_metrics",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="InteractionMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.UUIDField()),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("room_id", models.UUIDField(blank=True, null=True)),
                ("interaction_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "interaction_metrics",
                "ordering": ["-timestamp"],
            },
        ),
    ]
