# Generated by Django 5.2.4 on 2025-07-16 19:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.URLField()),
                ("source_type", models.CharField(max_length=50)),
                ("status", models.CharField(default="active", max_length=50)),
                ("last_crawled", models.DateTimeField(blank=True, null=True)),
                ("total_documents", models.IntegerField(default=0)),
                ("crawl_frequency", models.CharField(default="daily", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "document_sources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndexingProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("milestone", models.CharField(max_length=50)),
                ("target_documents", models.IntegerField()),
                ("current_documents", models.IntegerField(default=0)),
                ("current_percentage", models.FloatField(default=0.0)),
                ("unique_sources", models.IntegerField(default=0)),
                ("total_embeddings", models.IntegerField(default=0)),
                ("avg_processing_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "indexing_progress",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.UUIDField()),
                ("query_text", models.TextField()),
                ("query_type", models.CharField(max_length=50)),
                ("documents_retrieved", models.IntegerField(default=0)),
                ("response_time_ms", models.IntegerField()),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "knowledge_queries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="IndexingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_type", models.CharField(max_length=50)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("documents_processed", models.IntegerField(default=0)),
                ("documents_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.documentsource",
                    ),
                ),
            ],
            options={
                "db_table": "indexing_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=2000)),
                ("title", models.CharField(max_length=500)),
                ("content_type", models.CharField(max_length=100)),
                ("word_count", models.IntegerField(blank=True, null=True)),
                (
                    "embedding_status",
                    models.CharField(default="pending", max_length=50),
                ),
                ("embedding_dimensions", models.JSONField(blank=True, default=list)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.indexingjob",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.documentsource",
                    ),
                ),
            ],
            options={
                "db_table": "processed_documents",
                "ordering": ["-created_at"],
                "unique_together": {("source", "document_id")},
            },
        ),
    ]
