# Generated by Django 4.2.23 on 2025-07-16 02:30

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("username", models.TextField(blank=True, null=True)),
                ("system", models.TextField(blank=True, null=True)),
                ("bio", models.JSONField(default=list)),
                ("message_examples", models.JSONField(default=list)),
                ("post_examples", models.JSONField(default=list)),
                ("topics", models.JSONField(default=list)),
                ("adjectives", models.JSONField(default=list)),
                ("knowledge", models.JSONField(default=list)),
                ("plugins", models.JSONField(default=list)),
                ("settings", models.JSONField(default=dict)),
                ("style", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "agents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cache",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("agent_id", models.UUIDField()),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "cache",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CentralMessage",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("channel_id", models.TextField()),
                ("author_id", models.TextField()),
                ("content", models.TextField()),
                ("raw_message", models.JSONField(blank=True, null=True)),
                (
                    "in_reply_to_root_message_id",
                    models.TextField(blank=True, null=True),
                ),
                ("source_type", models.TextField(blank=True, null=True)),
                ("source_id", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_messages",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_id", models.UUIDField(db_column="entityId")),
                ("agent_id", models.UUIDField(db_column="agentId")),
                ("room_id", models.UUIDField(db_column="roomId")),
                (
                    "world_id",
                    models.UUIDField(blank=True, db_column="worldId", null=True),
                ),
                (
                    "source_entity_id",
                    models.UUIDField(blank=True, db_column="sourceEntityId", null=True),
                ),
                ("type", models.TextField()),
                ("data", models.JSONField(default=dict)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
            ],
            options={
                "db_table": "components",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("names", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "entities",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("entity_id", models.UUIDField(db_column="entityId")),
                ("body", models.JSONField()),
                ("type", models.TextField()),
                ("room_id", models.UUIDField(db_column="roomId")),
            ],
            options={
                "db_table": "logs",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                ("content", models.JSONField()),
                (
                    "entity_id",
                    models.UUIDField(blank=True, db_column="entityId", null=True),
                ),
                ("agent_id", models.UUIDField(db_column="agentId")),
                (
                    "room_id",
                    models.UUIDField(blank=True, db_column="roomId", null=True),
                ),
                (
                    "world_id",
                    models.UUIDField(blank=True, db_column="worldId", null=True),
                ),
                ("unique", models.BooleanField(default=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "memories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MessageServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("source_type", models.TextField()),
                ("source_id", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "message_servers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity_id",
                    models.UUIDField(blank=True, db_column="entityId", null=True),
                ),
                (
                    "room_id",
                    models.UUIDField(blank=True, db_column="roomId", null=True),
                ),
                (
                    "agent_id",
                    models.UUIDField(blank=True, db_column="agentId", null=True),
                ),
                (
                    "room_state",
                    models.TextField(blank=True, db_column="roomState", null=True),
                ),
            ],
            options={
                "db_table": "participants",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_entity_id", models.UUIDField(db_column="sourceEntityId")),
                ("target_entity_id", models.UUIDField(db_column="targetEntityId")),
                ("agent_id", models.UUIDField()),
                ("tags", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "relationships",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_id",
                    models.UUIDField(blank=True, db_column="agentId", null=True),
                ),
                ("source", models.TextField()),
                ("type", models.TextField()),
                (
                    "server_id",
                    models.TextField(blank=True, db_column="serverId", null=True),
                ),
                (
                    "world_id",
                    models.UUIDField(blank=True, db_column="worldId", null=True),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "channel_id",
                    models.TextField(blank=True, db_column="channelId", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
            ],
            options={
                "db_table": "rooms",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ServerAgent",
            fields=[
                ("server_id", models.UUIDField(primary_key=True, serialize=False)),
                ("agent_id", models.UUIDField()),
            ],
            options={
                "db_table": "server_agents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "room_id",
                    models.UUIDField(blank=True, db_column="roomId", null=True),
                ),
                (
                    "world_id",
                    models.UUIDField(blank=True, db_column="worldId", null=True),
                ),
                (
                    "entity_id",
                    models.UUIDField(blank=True, db_column="entityId", null=True),
                ),
                ("agent_id", models.UUIDField()),
                ("tags", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tasks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AgentMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.UUIDField(unique=True)),
                ("agent_name", models.CharField(max_length=255)),
                (
                    "deployment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_interactions", models.IntegerField(default=0)),
                ("total_documents_processed", models.IntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "agent_metrics",
                "ordering": ["-deployment_date"],
            },
        ),
        migrations.CreateModel(
            name="DocumentMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.UUIDField(blank=True, null=True)),
                ("document_id", models.CharField(max_length=255)),
                ("document_path", models.TextField()),
                ("document_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=500)),
                ("confidence_level", models.CharField(blank=True, max_length=50)),
                (
                    "processed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "document_metrics",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="InteractionMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.UUIDField()),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("room_id", models.UUIDField(blank=True, null=True)),
                ("interaction_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "interaction_metrics",
                "ordering": ["-timestamp"],
            },
        ),
    ]
